import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="page">
                <main>
                    <h1>Mongoose Activity</h1>
                    <ul>
                        <li><a href="/api/weather/zipcode/96815">
                            REST API weather for zipcode <code className={styles.code}>96815</code>
                        </a></li>
                        <li><a href="/api/graphql">GraphQL API weather</a></li>
                    </ul>
                </main>
            </div>
        </>
    );
}
